### ISSUE TITLE
Support for macos-latest host OS

### ISSUE THREAD

**Issue by igorbiscanin** [asadmansr/android-test-report-action#10]
Is it planned to add support for macos-latest host OS?

**Comment by asadmansr** [comment]
Hi @igorbiscanin, thank you for creating the issue. Unfortunately it seems like the container implementation only supports linux. Ideally, I would love to support macos but it might be a bit of work. 

As a workaround, you can update your workflow to save the reports as artifacts and run the action as a separate job using ubuntu. For example:

```
name: Android CI
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: app/build/test-results
        

  report:
    runs-on: ubuntu-latest
    needs: test # Run after test job
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0

```

Example: https://github.com/asadmansr/android-test-report-action-example/actions/runs/94056432

In the meantime, I'll keep this issue open for any development on this work.
