### ISSUE TITLE
Support for Gradle multi-module project

### ISSUE THREAD

**Issue by cvillaseca** [asadmansr/android-test-report-action#14]
Hi 👋 

I was trying this Github Action and I noticed that the report generated takes only the XML tests results inside the main module (app), the rest of the reports are inside the `build/test-results` of each module. Are you planning to support multi-module projects soon? 

Thanks

**Comment by cvillaseca** [comment]
I was able to fix it using a wildcard 
```
      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: '**/build/test-results'
 ```
